// PLAYER ACTIONS

export const DEFLECT_TOP = 'DEFLECT_TOP';
export const DEFLECT_CENTER = 'DEFLECT_CENTER';
export const DEFLECT_DOWN = 'DEFLECT_DOWN';
export const BLOCK = 'BLOCK';
export const DODGE = 'DODGE';
export const JUMP = 'JUMP';

export const SELECT_NEXT_PLAYER_ACTION = 'SELECT_NEXT_PLAYER_ACTION';
export const READY_TO_FIGHT = 'READY_TO_FIGHT';
export const READY_TO_FIGHT_ANIMATE = 'READY_TO_FIGHT_ANIMATE';
export const CHANGE_ENEMY = 'CHANGE_ENEMY';
export const NEXT_ENEMY = 'NEXT_ENEMY';
export const END_TURN = 'END_TURN';
export const START_BATTLE = 'START_BATTLE';
export const START_NEW_TURN = 'START_NEW_TURN';
export const ATTACKING_START = 'ATTACKING_START';
export const ATTACKING_END = 'ATTACKING_END';

export const UPDATE_TIMER = 'UPDATE_TIMER';

// ENEMY ACTIONS

export const ATTACK_TOP = 'ATTACK_TOP';
export const ATTACK_CENTER = 'ATTACK_CENTER';
export const ATTACK_DOWN = 'ATTACK_DOWN';
export const IMPALE = 'IMPALE';
export const SWEEP = 'SWEEP';

// BATTLE ACTIONS

export const ATTACK_HIT = 'ATTACK_HIT';
export const ATTACK_BLOCKED = 'ATTACK_BLOCKED';
export const ATTACK_DEFLECTED = 'ATTACK_DEFLECTED';
export const ATTACK_DODGED = 'ATTACK_DODGED';
export const IMPALE_HIT = 'IMPALE_HIT';
export const IMPALE_COUNTERED = 'IMPALE_COUNTERED';
export const IMPALE_DEFLECTED = 'IMPALE_DEFLECTED';
export const SWEEP_HIT = 'SWEEP_HIT';
export const SWEEP_DEFLECTED = 'SWEEP_DEFLECTED';
export const SWEEP_COUNTERED = 'SWEEP_COUNTERED';

export const NEXT_ENEMY_MOVE = 'NEXT_ENEMY_MOVE'
export const NEXT_ENEMY_ATTACK = 'NEXT_ENEMY_ATTACK';
export const NEXT_ENEMY_MOVESET = 'NEXT_ENEMY_MOVESET';

// USER ACTIONS

export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const REQUEST_HIGHSCORES = 'REQUEST_HIGHSCORES';
export const GET_HIGHSCORES = 'GET_HIGHSCORES';
export const RESTART_LEVEL = 'RESTART_LEVEL';
